package controller

import (
	"context"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	kdexv1alpha1 "kdex.dev/crds/api/v1alpha1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

var _ = Describe("KDexFunction Codegen", func() {
	Context("When reconciling a KDexFunction", func() {
		const resourceName = "test-function"
		ctx := context.Background()

		AfterEach(func() {
			cleanupResources(namespace)
		})

		It("becomes BuildValid", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: "some-host"},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Function: kdexv1alpha1.KDexFunctionExec{
						Environment: "go-env",
						Language:    "go",
						GeneratorConfig: &kdexv1alpha1.GeneratorConfig{
							Git: kdexv1alpha1.Git{
								Image:          "alpine:3.19",
								CommitterEmail: "test@kdex.dev",
								CommitterName:  "KDex Codegen Bot",
								RepoSecretRef: corev1.LocalObjectReference{
									Name: "gitea-job-config",
								},
							},
							Image: "k3d-registry:5000/kdex-tech/fngogen",
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			addOrUpdateHost(
				ctx, k8sClient,
				kdexv1alpha1.KDexHost{
					ObjectMeta: metav1.ObjectMeta{
						Name:      "some-host",
						Namespace: namespace,
					},
					Spec: kdexv1alpha1.KDexHostSpec{
						BrandName:    "KDex Tech",
						Organization: "KDex Tech Inc.",
						Routing: kdexv1alpha1.Routing{
							Domains: []string{
								"kdex.dev",
							},
						},
					},
				},
			)

			assertResourceReady(
				ctx, k8sClient, "some-host", namespace,
				&kdexv1alpha1.KDexHost{}, true)

			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: resource.Name, Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateBuildValid))
				g.Expect(
					meta.IsStatusConditionFalse(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeDegraded),
					),
				).To(BeTrue())
				g.Expect(
					meta.IsStatusConditionTrue(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeProgressing),
					),
				).To(BeTrue())
				g.Expect(
					meta.IsStatusConditionFalse(
						fetched.Status.Conditions,
						string(kdexv1alpha1.ConditionTypeReady),
					),
				).To(BeTrue())
				cond := meta.FindStatusCondition(
					fetched.Status.Conditions,
					string(kdexv1alpha1.ConditionTypeProgressing),
				)
				g.Expect(cond.Message).To(Equal(string(kdexv1alpha1.KDexFunctionStateBuildValid)))
			}, "10s", "1s").Should(Succeed())
		})
	})
})
