package controller

import (
	"context"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	kdexv1alpha1 "kdex.dev/crds/api/v1alpha1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

var _ = Describe("KDexFunction Controller", func() {
	Context("When reconciling a KDexFunction", func() {
		const resourceName = "test-function"
		ctx := context.Background()

		AfterEach(func() {
			cleanupResources(namespace)
		})

		It("should successfully reconcile a manual function to Ready", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: "some-host"},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: false,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
					Function: kdexv1alpha1.KDexFunctionExec{
						Language:    "go",
						CodePackage: "oci://some-registry/some-package",
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: resourceName, Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())
				g.Expect(fetched.Status.State).To(Equal(kdexv1alpha1.KDexFunctionStateReady))
			}, "10s", "1s").Should(Succeed())
		})

		It("should transition to StubGenerated for auto-generated functions (Scaffolding)", func() {
			resource := &kdexv1alpha1.KDexFunction{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "test-auto-gen",
					Namespace: namespace,
				},
				Spec: kdexv1alpha1.KDexFunctionSpec{
					HostRef: corev1.LocalObjectReference{Name: "some-host"},
					Metadata: kdexv1alpha1.KDexFunctionMetadata{
						AutoGenerated: true,
					},
					API: kdexv1alpha1.API{
						BasePath: "/v1/api",
						Paths: map[string]kdexv1alpha1.PathItem{
							"/v1/api/test": {},
						},
					},
				},
			}

			Expect(k8sClient.Create(ctx, resource)).To(Succeed())

			Eventually(func(g Gomega) {
				fetched := &kdexv1alpha1.KDexFunction{}
				err := k8sClient.Get(ctx, client.ObjectKey{Name: "test-auto-gen", Namespace: namespace}, fetched)
				g.Expect(err).NotTo(HaveOccurred())

				stateOk := fetched.Status.State == kdexv1alpha1.KDexFunctionStateStubGenerated
				conds := fetched.Status.Conditions
				hasError := false
				for _, c := range conds {
					if c.Reason == string(kdexv1alpha1.ConditionReasonReconcileError) {
						hasError = true
						break
					}
				}
				g.Expect(stateOk || hasError).To(BeTrue())
			}, "10s", "1s").Should(Succeed())
		})
	})
})
