package webhook

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/daveshanley/vacuum/model"
	"github.com/daveshanley/vacuum/motor"
	"github.com/daveshanley/vacuum/rulesets"
	"k8s.io/apimachinery/pkg/runtime"
	kdexv1alpha1 "kdex.dev/crds/api/v1alpha1"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// +kubebuilder:webhook:path=/validate-kdex-dev-v1alpha1-kdexfunction,mutating=false,failurePolicy=fail,sideEffects=None,groups=kdex.dev,resources=kdexfunctions;kdexfunctions/status,verbs=create;update,versions=v1alpha1,name=validate.kdexfunction.kdex.dev,admissionReviewVersions=v1

type KDexFunctionValidator[T runtime.Object] struct {
}

var _ admission.Validator[*kdexv1alpha1.KDexFunction] = &KDexFunctionValidator[*kdexv1alpha1.KDexFunction]{}

func (v *KDexFunctionValidator[T]) ValidateCreate(ctx context.Context, obj T) (admission.Warnings, error) {
	return v.validate(ctx, obj)
}

func (v *KDexFunctionValidator[T]) ValidateUpdate(ctx context.Context, oldObj, newObj T) (admission.Warnings, error) {
	return v.validate(ctx, newObj)
}

func (v *KDexFunctionValidator[T]) ValidateDelete(ctx context.Context, obj T) (admission.Warnings, error) {
	return nil, nil
}

func (v *KDexFunctionValidator[T]) validate(_ context.Context, obj T) (admission.Warnings, error) {
	var function *kdexv1alpha1.KDexFunction

	switch t := any(obj).(type) {
	case *kdexv1alpha1.KDexFunction:
		function = t
	default:
		return nil, fmt.Errorf("unsupported type: %T", t)
	}

	spec := &function.Spec

	// 1. Structural Validation
	if spec.HostRef.Name == "" {
		return nil, fmt.Errorf("spec.hostRef.name must not be empty")
	}

	re := spec.API.BasePathRegex()
	if !re.MatchString(spec.API.BasePath) {
		return nil, fmt.Errorf("spec.api.basePath %s does not match %s", spec.API.BasePath, re.String())
	}

	re = spec.API.ItemPathRegex()
	for curPath := range spec.API.Paths {
		if !re.MatchString(curPath) {
			return nil, fmt.Errorf("spec.api.paths[%s] does not match %s", curPath, re.String())
		}
	}

	// 2. OpenAPI Validation using vacuum
	if err := v.validateOpenAPI(spec); err != nil {
		return nil, fmt.Errorf("OpenAPI validation failed: %w", err)
	}

	// 3. Implementation Validation for Manual Functions
	if !spec.Metadata.AutoGenerated {
		if spec.Function.Language == "" {
			return nil, fmt.Errorf("spec.function.language is required for manual functions")
		}
		if spec.Function.CodePackage == "" {
			return nil, fmt.Errorf("spec.function.codePackage is required for manual functions")
		}
	}

	// 4. State Integrity Validation
	if function.Status.State == kdexv1alpha1.KDexFunctionStateReady {
		// A Ready function must have a deployable package (manual) or a generated image (automated)
		hasImplementation := spec.Function.CodePackage != "" ||
			(function.Status.StubDetails != nil && function.Status.StubDetails.SourceImage != "")

		if !hasImplementation {
			return nil, fmt.Errorf("function cannot be in Ready state without a codePackage or valid SourceImage")
		}
	}

	return nil, nil
}

func (v *KDexFunctionValidator[T]) validateOpenAPI(spec *kdexv1alpha1.KDexFunctionSpec) error {
	// Build a minimal OpenAPI 3.0 document from the spec.API
	openAPIDoc := map[string]interface{}{
		"openapi": "3.0.3",
		"info": map[string]interface{}{
			"title":   "Function API",
			"version": "1.0.0",
		},
		"paths": map[string]interface{}{},
		"components": map[string]interface{}{
			"responses": map[string]interface{}{
				"BadRequest": map[string]interface{}{
					"description": "Bad Request",
				},
				"Found": map[string]interface{}{
					"description": "Found",
				},
				"InternalServerError": map[string]interface{}{
					"description": "Internal Server Error",
				},
				"NotFound": map[string]interface{}{
					"description": "Not Found",
				},
				"SeeOther": map[string]interface{}{
					"description": "See Other",
				},
				"Unauthorized": map[string]interface{}{
					"description": "Unauthorized",
				},
			},
		},
	}

	// Convert spec.API.Paths to standard OpenAPI paths
	paths := make(map[string]interface{})
	for pathKey, pathItem := range spec.API.Paths {
		pathObj := make(map[string]interface{})

		if pathItem.Description != "" {
			pathObj["description"] = pathItem.Description
		}
		if pathItem.Summary != "" {
			pathObj["summary"] = pathItem.Summary
		}

		// Add operations
		if pathItem.Get != nil {
			var op map[string]interface{}
			if err := json.Unmarshal(pathItem.Get.Raw, &op); err == nil {
				pathObj["get"] = op
			}
		}
		if pathItem.Post != nil {
			var op map[string]interface{}
			if err := json.Unmarshal(pathItem.Post.Raw, &op); err == nil {
				pathObj["post"] = op
			}
		}
		if pathItem.Put != nil {
			var op map[string]interface{}
			if err := json.Unmarshal(pathItem.Put.Raw, &op); err == nil {
				pathObj["put"] = op
			}
		}
		if pathItem.Delete != nil {
			var op map[string]interface{}
			if err := json.Unmarshal(pathItem.Delete.Raw, &op); err == nil {
				pathObj["delete"] = op
			}
		}
		if pathItem.Patch != nil {
			var op map[string]interface{}
			if err := json.Unmarshal(pathItem.Patch.Raw, &op); err == nil {
				pathObj["patch"] = op
			}
		}

		paths[pathKey] = pathObj
	}
	openAPIDoc["paths"] = paths

	// Add schemas if present
	if len(spec.API.Schemas) > 0 {
		schemas := make(map[string]interface{})
		for schemaKey, schemaRaw := range spec.API.Schemas {
			var schema map[string]interface{}
			if err := json.Unmarshal(schemaRaw.Raw, &schema); err == nil {
				schemas[schemaKey] = schema
			}
		}
		// Add schemas to existing components
		if components, ok := openAPIDoc["components"].(map[string]interface{}); ok {
			components["schemas"] = schemas
		}
	}

	// Marshal to JSON for vacuum
	specBytes, err := json.Marshal(openAPIDoc)
	if err != nil {
		return fmt.Errorf("failed to marshal OpenAPI spec: %w", err)
	}

	// Run vacuum linter
	results, err := lintOpenAPISpec(specBytes)
	if err != nil {
		return fmt.Errorf("linting error: %w", err)
	}

	// Check for errors in results
	var errorMessages []string
	for _, result := range results {
		// Only fail on errors, not warnings
		if result.Rule.Severity == "error" {
			errorMessages = append(errorMessages, fmt.Sprintf("%s: %s", result.Rule.Name, result.Message))
		}
	}

	if len(errorMessages) > 0 {
		return fmt.Errorf("OpenAPI spec validation errors: %s", strings.Join(errorMessages, "; "))
	}

	return nil
}

func lintOpenAPISpec(spec []byte) ([]model.RuleFunctionResult, error) {
	// Use default rulesets
	defaultRuleSets := rulesets.BuildDefaultRuleSets()
	selectedRuleSet := defaultRuleSets.GenerateOpenAPIRecommendedRuleSet()

	// Filter to only OAS 3.0.x rules
	for id, rule := range selectedRuleSet.Rules {
		// Skip example rules as they can be too strict
		if id == "oas3-missing-example" {
			delete(selectedRuleSet.Rules, id)
		}

		isOAS3 := false
		for _, f := range rule.Formats {
			if f == "oas3" {
				isOAS3 = true
				break
			}
		}
		if !isOAS3 {
			delete(selectedRuleSet.Rules, id)
		}
	}

	results := motor.ApplyRulesToRuleSet(&motor.RuleSetExecution{
		RuleSet: selectedRuleSet,
		Spec:    spec,
	})

	return results.Results, nil
}
